name: Container image build and push

on:
  workflow_dispatch:
  
jobs:

  build-and-push:

    runs-on: ubuntu-latest

    steps:
    - name: Login to registry
      run: | 
        #push to registry
        echo ${{ secrets.DOCKERHUB_ACCESS_TOKEN }} | docker login --username kazhar --password-stdin
